version: 2.1

jobs:
  build:
    docker:
      - image: google/dart:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pub get

      - run:
          name: Run tests
          command: dart test ./rice_cooker_test.dart
