version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.15 
    working_directory: /go/src/github.com/hei-school/cc-d4-rice-cooker-ci-Ezdev2/

    steps:
      - checkout

      # Exécutez les tests
      - run:
          name: Run Tests
          command: go test -v

workflows:
  version: 2
  build:
    jobs:
      - build
