version: 2.1

jobs:
  test:
    docker:
      - image: rocker/r-ver:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: Rscript -e 'install.packages(c("testthat"))'
      - run:
          name: Run tests
          command: Rscript -e 'testthat::test_file("test_rice_cooker.R")'
